name: Prettier Check

on:
  [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies in client
      run: |
        cd client
        npm ci

    - name: Install dependencies in server
      run: |
        cd server
        npm ci

    - name: Check client formatting
      run: |
        cd client
        npx prettier --check "**/*.{js,ts,html,css,scss}"

    - name: Check server formatting
      run: |
        cd server
        npx prettier --check "**/*.js"